(in-package "RTL")

(include-book "types")
(include-book "vdot")


(defthm partialsproducts8-loop-0-type
  (implies (and (is-type-p i '(int))
                (is-type-p bval '(int))
                (is-type-p pps '(array (bvec 12) 5))
                (is-type-p b_encs '(array (int) 5)))
           (is-type-p (partialsproducts8-loop-0 i bval b_encs pps)
                      '(array (bvec 12) 5)))
  :hints (("Goal"
           :in-theory '(partialsproducts8-loop-0 type-theory))))

(defthm partialsproducts8-type
  (implies (and (is-type-p b '(bvec 8))
                (is-type-p b_encs '(array (int) 5))
                (is-type-p bsigned '(bool)))
           (is-type-p (partialsproducts8 b b_encs bsigned)
                      '(array (bvec 12) 5)))
  :hints (("Goal"
           :in-theory '(partialsproducts8 partialsproducts8-loop-0-type type-theory))))

(defun lane-inputs-ok-p (opa opb acc opa_unsigned opb_unsigned size without_vdot16)
  (and (bvecp opa 64)
       (bvecp opb 64)
       (bvecp acc 64)
       (bitp opa_unsigned)
       (bitp opb_unsigned)
       (bitp size)
       (bitp without_vdot16)
       (implies (equal size 1) (equal without_vdot16 0))))

(local
  (encapsulate
    (((opa) => *)
     ((opb) => *)
     ((acc) => *)
     ((opa_unsigned) => *)
     ((opb_unsigned) => *)
     ((size) => *)
     ((without_vdot16) => *))
    (local (defund opa () 0))
    (local (defund opb () 0))
    (local (defund acc () 0))
    (local (defund opa_unsigned () 0))
    (local (defund opb_unsigned () 0))
    (local (defund size () 0))
    (local (defund without_vdot16 () 0))
    (defthmd inputs-ok
      (lane-inputs-ok-p (opa)
                   (opb)
                   (acc)
                   (opa_unsigned)
                   (opb_unsigned)
                   (size)
                   (without_vdot16))
      :hints (("Goal"
               :in-theory (enable opa opb acc opa_unsigned opb_unsigned size without_vdot16))))))

(include-book "rtl/rel11/lib/top" :dir :system)
(local (include-book "projects/arm/utils/rtl-utils" :dir :system))

(local (bvecthm opa-vec (bvecp (opa) 64) :hints (("Goal" :use inputs-ok))))
(local (bvecthm opb-vec (bvecp (opb) 64) :hints (("Goal" :use inputs-ok))))
(local (bvecthm acc-vec (bvecp (acc) 64) :hints (("Goal" :use inputs-ok))))
(local (bitthm opa_unsigned-vec (bitp (opa_unsigned)) :hints (("Goal" :use inputs-ok))))
(local (bitthm opb_unsigned-vec (bitp (opb_unsigned)) :hints (("Goal" :use inputs-ok))))
(local (bitthm size-bit (bitp (size)) :hints (("Goal" :use inputs-ok))))
(local (bitthm without_vdot16-bit (bitp (without_vdot16)) :hints (("Goal" :use inputs-ok))))

(local (include-book "../lisp/alt-const-fns-gen"))

;;:ubt lane-res
;;  (make-event
;    (acl2::alt-const-fns-gen
;      'lane-res
;     t
;     '(DEFUN LANE (OPA OPB ACC OPA_UNSIGNED
;                                OPB_UNSIGNED SIZE WITHOUT_VDOT16)
;                (LET*
;                 ((PP (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
;                                                  (CONS 1 0)
;                                                  (CONS 2 0)
;                                                  (CONS 3 0)
;                                                  (CONS 4 0)
;                                                  (CONS 5 0)
;                                                  (CONS 6 0)
;                                                  (CONS 7 0)
;                                                  (CONS 8 0)
;                                                  (CONS 9 0)
;                                                  (CONS 10 0)
;                                                  (CONS 11 0)
;                                                  (CONS 12 0)
;                                                  (CONS 13 0)
;                                                  (CONS 14 0)
;                                                  (CONS 15 0)
;                                                  (CONS 16 0)
;                                                  (CONS 17 0)
;                                                  (CONS 18 0)
;                                                  (CONS 19 0)
;                                                  (CONS 20 0)
;                                                  (CONS 21 0)
;                                                  (CONS 22 0)
;                                                  (CONS 23 0)
;                                                  (CONS 24 0)
;                                                  (CONS 25 0)
;                                                  (CONS 26 0)
;                                                  (CONS 27 0)
;                                                  (CONS 28 0)
;                                                  (CONS 29 0)
;                                                  (CONS 30 0)
;                                                  (CONS 31 0)
;                                                  (CONS 32 0)
;                                                  (CONS 33 0)
;                                                  (CONS 34 0)
;                                                  (CONS 35 0)
;                                                  (CONS 36 0)
;                                                  (CONS 37 0)
;                                                  (CONS 38 0)
;                                                  (CONS 39 0)))
;                                     '(ARRAY (BVEC 20) 40)))
;                  (PP (LANE-LOOP-8 (RAC-TYPE-INFO 0 '(INT))
;                                   PP))
;                  (:PP
;                   (IF1
;                    SIZE
;                    (LET ((A (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
;                                                         (CONS 1 0)
;                                                         (CONS 2 0)
;                                                         (CONS 3 0)))
;                                            '(ARRAY (BVEC 16) 4)))
;                          (B (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
;                                                         (CONS 1 0)
;                                                         (CONS 2 0)
;                                                         (CONS 3 0)))
;                                            '(ARRAY (BVEC 16) 4))))
;                     (MV-LET (:A :B)
;                             (LANE-LOOP-7 (RAC-TYPE-INFO 0 '(INT))
;                                          OPA OPB A B)
;                      (LET
;                       ((B_ENCS (RAC-TYPE-INFO (AINIT (LIST (CONS 0 NIL)
;                                                            (CONS 1 NIL)
;                                                            (CONS 2 NIL)
;                                                            (CONS 3 NIL)))
;                                               '(ARRAY (ARRAY (INT) 9) 4)))
;                        (PPS_ALIGNED
;                         (RAC-TYPE-INFO
;                              (AINIT (LIST (CONS 0
;                                                 (AINIT (LIST (CONS 0 0)
;                                                              (CONS 1 0)
;                                                              (CONS 2 0)
;                                                              (CONS 3 0)
;                                                              (CONS 4 0)
;                                                              (CONS 5 0)
;                                                              (CONS 6 0)
;                                                              (CONS 7 0)
;                                                              (CONS 8 0))))
;                                           (CONS 1
;                                                 (AINIT (LIST (CONS 0 0)
;                                                              (CONS 1 0)
;                                                              (CONS 2 0)
;                                                              (CONS 3 0)
;                                                              (CONS 4 0)
;                                                              (CONS 5 0)
;                                                              (CONS 6 0)
;                                                              (CONS 7 0)
;                                                              (CONS 8 0))))
;                                           (CONS 2
;                                                 (AINIT (LIST (CONS 0 0)
;                                                              (CONS 1 0)
;                                                              (CONS 2 0)
;                                                              (CONS 3 0)
;                                                              (CONS 4 0)
;                                                              (CONS 5 0)
;                                                              (CONS 6 0)
;                                                              (CONS 7 0)
;                                                              (CONS 8 0))))
;                                           (CONS 3
;                                                 (AINIT (LIST (CONS 0 0)
;                                                              (CONS 1 0)
;                                                              (CONS 2 0)
;                                                              (CONS 3 0)
;                                                              (CONS 4 0)
;                                                              (CONS 5 0)
;                                                              (CONS 6 0)
;                                                              (CONS 7 0)
;                                                              (CONS 8 0))))))
;                              '(ARRAY (ARRAY (BVEC 20) 9) 4))))
;                       (MV-LET
;                             (B_ENCS PPS_ALIGNED)
;                             (LANE-LOOP-6 (RAC-TYPE-INFO 0 '(INT))
;                                          A OPA_UNSIGNED
;                                          B OPB_UNSIGNED B_ENCS PPS_ALIGNED)
;                        (LET*
;                         ((PP (LANE-LOOP-5 (RAC-TYPE-INFO 0 '(INT))
;                                           PPS_ALIGNED PP))
;                          (PP
;                           (AS 32
;                               (BITS (- (AG 8 (AG 0 PPS_ALIGNED)) (ASH 1 18))
;                                     19 0)
;                               PP))
;                          (PP
;                             (AS 32
;                                 (SETBITN (AG 32 PP)
;                                          20 0 (LOG< (AG 7 (AG 0 B_ENCS)) 0))
;                                 PP))
;                          (PP (AS 33 349536 PP))
;                          (PP
;                           (AS 34
;                               (BITS (- (AG 8 (AG 1 PPS_ALIGNED)) (ASH 1 18))
;                                     19 0)
;                               PP))
;                          (PP
;                             (AS 34
;                                 (SETBITN (AG 34 PP)
;                                          20 0 (LOG< (AG 7 (AG 1 B_ENCS)) 0))
;                                 PP))
;                          (PP
;                           (AS 36
;                               (BITS (- (AG 8 (AG 2 PPS_ALIGNED)) (ASH 1 18))
;                                     19 0)
;                               PP))
;                          (PP
;                             (AS 36
;                                 (SETBITN (AG 36 PP)
;                                          20 0 (LOG< (AG 7 (AG 2 B_ENCS)) 0))
;                                 PP))
;                          (PP
;                           (AS 38
;                               (BITS (- (AG 8 (AG 3 PPS_ALIGNED)) (ASH 1 18))
;                                     19 0)
;                               PP)))
;                         (AS 38
;                             (SETBITN (AG 38 PP)
;                                      20 0 (LOG< (AG 7 (AG 3 B_ENCS)) 0))
;                             PP))))))
;                    (LET ((A (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
;                                                         (CONS 1 0)
;                                                         (CONS 2 0)
;                                                         (CONS 3 0)
;                                                         (CONS 4 0)
;                                                         (CONS 5 0)
;                                                         (CONS 6 0)
;                                                         (CONS 7 0)))
;                                            '(ARRAY (BVEC 8) 8)))
;                          (B (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
;                                                         (CONS 1 0)
;                                                         (CONS 2 0)
;                                                         (CONS 3 0)
;                                                         (CONS 4 0)
;                                                         (CONS 5 0)
;                                                         (CONS 6 0)
;                                                         (CONS 7 0)))
;                                            '(ARRAY (BVEC 8) 8))))
;                     (MV-LET (A B)
;                             (LANE-LOOP-4 (RAC-TYPE-INFO 0 '(INT))
;                                          OPA OPB A B)
;                      (LET
;                       ((B_ENCS (RAC-TYPE-INFO (AINIT (LIST (CONS 0 NIL)
;                                                            (CONS 1 NIL)
;                                                            (CONS 2 NIL)
;                                                            (CONS 3 NIL)
;                                                            (CONS 4 NIL)
;                                                            (CONS 5 NIL)
;                                                            (CONS 6 NIL)
;                                                            (CONS 7 NIL)))
;                                               '(ARRAY (ARRAY (INT) 5) 8)))
;                        (PPS_ALIGNED
;                         (RAC-TYPE-INFO
;                              (AINIT (LIST (CONS 0
;                                                 (AINIT (LIST (CONS 0 0)
;                                                              (CONS 1 0)
;                                                              (CONS 2 0)
;                                                              (CONS 3 0)
;                                                              (CONS 4 0))))
;                                           (CONS 1
;                                                 (AINIT (LIST (CONS 0 0)
;                                                              (CONS 1 0)
;                                                              (CONS 2 0)
;                                                              (CONS 3 0)
;                                                              (CONS 4 0))))
;                                           (CONS 2
;                                                 (AINIT (LIST (CONS 0 0)
;                                                              (CONS 1 0)
;                                                              (CONS 2 0)
;                                                              (CONS 3 0)
;                                                              (CONS 4 0))))
;                                           (CONS 3
;                                                 (AINIT (LIST (CONS 0 0)
;                                                              (CONS 1 0)
;                                                              (CONS 2 0)
;                                                              (CONS 3 0)
;                                                              (CONS 4 0))))
;                                           (CONS 4
;                                                 (AINIT (LIST (CONS 0 0)
;                                                              (CONS 1 0)
;                                                              (CONS 2 0)
;                                                              (CONS 3 0)
;                                                              (CONS 4 0))))
;                                           (CONS 5
;                                                 (AINIT (LIST (CONS 0 0)
;                                                              (CONS 1 0)
;                                                              (CONS 2 0)
;                                                              (CONS 3 0)
;                                                              (CONS 4 0))))
;                                           (CONS 6
;                                                 (AINIT (LIST (CONS 0 0)
;                                                              (CONS 1 0)
;                                                              (CONS 2 0)
;                                                              (CONS 3 0)
;                                                              (CONS 4 0))))
;                                           (CONS 7
;                                                 (AINIT (LIST (CONS 0 0)
;                                                              (CONS 1 0)
;                                                              (CONS 2 0)
;                                                              (CONS 3 0)
;                                                              (CONS 4 0))))))
;                              '(ARRAY (ARRAY (BVEC 12) 5) 8))))
;                       (MV-LET
;                             (B_ENCS PPS_ALIGNED)
;                             (LANE-LOOP-3 (RAC-TYPE-INFO 0 '(INT))
;                                          A OPA_UNSIGNED
;                                          B OPB_UNSIGNED B_ENCS PPS_ALIGNED)
;                         (LET* ((PP (LANE-LOOP-2 (RAC-TYPE-INFO 0 '(INT))
;                                                 PPS_ALIGNED PP))
;                                (PP (LANE-LOOP-1 (RAC-TYPE-INFO 0 '(INT))
;                                                 PPS_ALIGNED B_ENCS PP)))
;                           (AS 4 (BITS (+ (AG 4 PP) 704512) 19 0)
;                               PP)))))))))
;                 (IF1
;                     WITHOUT_VDOT16
;                     (LET ((L0PP (RAC-TYPE-INFO (CONVERT_PP PP)
;                                                '(ARRAY (BVEC 21) 40)))
;                           (PPS (RAC-TYPE-INFO 0 '(BVEC 21)))
;                           (PPC (RAC-TYPE-INFO 0 '(BVEC 21))))
;                       (MV-LET (PPS PPC)
;                               (COMPRESS_WITHOUT_VDOT16 L0PP)
;                         (LET ((SUM_PP (RAC-TYPE-INFO (BITS (+ PPS PPC) 20 0)
;                                                      '(BVEC 21))))
;                           (BITS (+ (+ SUM_PP ACC) 4293918720)
;                                 63 0))))
;                     (LET* ((L0PP (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
;                                                              (CONS 1 0)
;                                                              (CONS 2 0)
;                                                              (CONS 3 0)
;                                                              (CONS 4 0)
;                                                              (CONS 5 0)
;                                                              (CONS 6 0)
;                                                              (CONS 7 0)
;                                                              (CONS 8 0)
;                                                              (CONS 9 0)
;                                                              (CONS 10 0)
;                                                              (CONS 11 0)
;                                                              (CONS 12 0)
;                                                              (CONS 13 0)
;                                                              (CONS 14 0)
;                                                              (CONS 15 0)
;                                                              (CONS 16 0)
;                                                              (CONS 17 0)
;                                                              (CONS 18 0)
;                                                              (CONS 19 0)
;                                                              (CONS 20 0)
;                                                              (CONS 21 0)
;                                                              (CONS 22 0)
;                                                              (CONS 23 0)
;                                                              (CONS 24 0)
;                                                              (CONS 25 0)
;                                                              (CONS 26 0)
;                                                              (CONS 27 0)
;                                                              (CONS 28 0)
;                                                              (CONS 29 0)
;                                                              (CONS 30 0)
;                                                              (CONS 31 0)
;                                                              (CONS 32 0)
;                                                              (CONS 33 0)
;                                                              (CONS 34 0)
;                                                              (CONS 35 0)
;                                                              (CONS 36 0)
;                                                              (CONS 37 0)
;                                                              (CONS 38 0)
;                                                              (CONS 39 0)))
;                                                 '(ARRAY (BVEC 36) 40)))
;                            (L0PP (LANE-LOOP-0 (RAC-TYPE-INFO 0 '(INT))
;                                               L0PP))
;                            (L0PP (AS 0 (BITS (ASH (AG 35 PP) 14) 35 0)
;                                      L0PP))
;                            (L0PP (AS 1 (BITS (ASH (AG 37 PP) 14) 35 0)
;                                      L0PP))
;                            (L0PP (AS 2 (BITS (ASH (AG 39 PP) 14) 35 0)
;                                      L0PP))
;                            (L0PP (AS 3 (AG 0 PP) L0PP))
;                            (L0PP (AS 4 (AG 8 PP) L0PP))
;                            (L0PP (AS 5 (AG 16 PP) L0PP))
;                            (L0PP (AS 6 (AG 24 PP) L0PP))
;                            (L0PP (AS 7 (AG 1 PP) L0PP))
;                            (L0PP (AS 8 (AG 9 PP) L0PP))
;                            (L0PP (AS 9 (AG 17 PP) L0PP))
;                            (L0PP (AS 10 (AG 25 PP) L0PP))
;                            (L0PP (AS 11 (BITS (ASH (AG 2 PP) 2) 35 0)
;                                      L0PP))
;                            (L0PP (AS 12 (BITS (ASH (AG 10 PP) 2) 35 0)
;                                      L0PP))
;                            (L0PP (AS 13 (BITS (ASH (AG 18 PP) 2) 35 0)
;                                      L0PP))
;                            (L0PP (AS 14 (BITS (ASH (AG 26 PP) 2) 35 0)
;                                      L0PP))
;                            (L0PP (AS 15 (BITS (ASH (AG 3 PP) 4) 35 0)
;                                      L0PP))
;                            (L0PP (AS 16 (BITS (ASH (AG 11 PP) 4) 35 0)
;                                      L0PP))
;                            (L0PP (AS 17 (BITS (ASH (AG 19 PP) 4) 35 0)
;                                      L0PP))
;                            (L0PP (AS 18 (BITS (ASH (AG 27 PP) 4) 35 0)
;                                      L0PP))
;                            (L0PP (AS 19 (BITS (ASH (AG 4 PP) 6) 35 0)
;                                      L0PP))
;                            (L0PP (AS 20 (BITS (ASH (AG 12 PP) 6) 35 0)
;                                      L0PP))
;                            (L0PP (AS 21 (BITS (ASH (AG 20 PP) 6) 35 0)
;                                      L0PP))
;                            (L0PP (AS 22 (BITS (ASH (AG 28 PP) 6) 35 0)
;                                      L0PP))
;                            (L0PP (AS 23 (BITS (ASH (AG 5 PP) 8) 35 0)
;                                      L0PP))
;                            (L0PP (AS 24 (BITS (ASH (AG 13 PP) 8) 35 0)
;                                      L0PP))
;                            (L0PP (AS 25 (BITS (ASH (AG 21 PP) 8) 35 0)
;                                      L0PP))
;                            (L0PP (AS 26 (BITS (ASH (AG 29 PP) 8) 35 0)
;                                      L0PP))
;                            (L0PP (AS 27 (BITS (ASH (AG 6 PP) 10) 35 0)
;                                      L0PP))
;                            (L0PP (AS 28 (BITS (ASH (AG 14 PP) 10) 35 0)
;                                      L0PP))
;                            (L0PP (AS 29 (BITS (ASH (AG 22 PP) 10) 35 0)
;                                      L0PP))
;                            (L0PP (AS 30 (BITS (ASH (AG 30 PP) 10) 35 0)
;                                      L0PP))
;                            (L0PP (AS 31 (BITS (ASH (AG 7 PP) 12) 35 0)
;                                      L0PP))
;                            (L0PP (AS 32 (BITS (ASH (AG 15 PP) 12) 35 0)
;                                      L0PP))
;                            (L0PP (AS 33 (BITS (ASH (AG 23 PP) 12) 35 0)
;                                      L0PP))
;                            (L0PP (AS 34 (BITS (ASH (AG 31 PP) 12) 35 0)
;                                      L0PP))
;                            (L0PP (AS 35 (BITS (ASH (AG 32 PP) 14) 35 0)
;                                      L0PP))
;                            (L0PP (AS 36 (BITS (ASH (AG 34 PP) 14) 35 0)
;                                      L0PP))
;                            (L0PP (AS 37 (BITS (ASH (AG 36 PP) 14) 35 0)
;                                      L0PP))
;                            (L0PP (AS 38 (BITS (ASH (AG 38 PP) 14) 35 0)
;                                      L0PP))
;                            (L0PP (AS 39 (BITS (ASH (AG 33 PP) 14) 35 0)
;                                      L0PP))
;                            (PPS (RAC-TYPE-INFO 0 '(BVEC 36)))
;                            (PPC (RAC-TYPE-INFO 0 '(BVEC 36))))
;                       (MV-LET (:PPS :PPC)
;                               (COMPRESS L0PP)
;                         (LET ((SUM_PP (RAC-TYPE-INFO (BITS (+ PPS PPC) 35 0)
;                                                      '(BVEC 36))))
;                           (IF1 SIZE
;                                (BITS (+ (+ SUM_PP ACC) 18446744039349813248)
;                                      63 0)
;                                (BITS (+ (+ (ASH SUM_PP (- 8))
;                                            18446744073708503040)
;                                         ACC)
;                                      63 0))))))))
;     )
;    )

(DEFUNDD A NIL
          (B* ((A (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                              (CONS 1 0)
                                              (CONS 2 0)
                                              (CONS 3 0)))
                                 '(ARRAY (BVEC 16) 4)))
               (B (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                              (CONS 1 0)
                                              (CONS 2 0)
                                              (CONS 3 0)))
                                 '(ARRAY (BVEC 16) 4))))
            (MV-NTH 0
                    (MV-LIST 2
                             (LANE-LOOP-7 (RAC-TYPE-INFO 0 '(INT))
                                          (OPA)
                                          (OPB)
                                          A B)))))
 (DEFUNDD B NIL
          (B* ((A (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                              (CONS 1 0)
                                              (CONS 2 0)
                                              (CONS 3 0)))
                                 '(ARRAY (BVEC 16) 4)))
               (B (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                              (CONS 1 0)
                                              (CONS 2 0)
                                              (CONS 3 0)))
                                 '(ARRAY (BVEC 16) 4))))
            (MV-NTH 1
                    (MV-LIST 2
                             (LANE-LOOP-7 (RAC-TYPE-INFO 0 '(INT))
                                          (OPA)
                                          (OPB)
                                          A B)))))
 (DEFUNDD
  PP NIL
  (B* ((PP (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                       (CONS 1 0)
                                       (CONS 2 0)
                                       (CONS 3 0)
                                       (CONS 4 0)
                                       (CONS 5 0)
                                       (CONS 6 0)
                                       (CONS 7 0)
                                       (CONS 8 0)
                                       (CONS 9 0)
                                       (CONS 10 0)
                                       (CONS 11 0)
                                       (CONS 12 0)
                                       (CONS 13 0)
                                       (CONS 14 0)
                                       (CONS 15 0)
                                       (CONS 16 0)
                                       (CONS 17 0)
                                       (CONS 18 0)
                                       (CONS 19 0)
                                       (CONS 20 0)
                                       (CONS 21 0)
                                       (CONS 22 0)
                                       (CONS 23 0)
                                       (CONS 24 0)
                                       (CONS 25 0)
                                       (CONS 26 0)
                                       (CONS 27 0)
                                       (CONS 28 0)
                                       (CONS 29 0)
                                       (CONS 30 0)
                                       (CONS 31 0)
                                       (CONS 32 0)
                                       (CONS 33 0)
                                       (CONS 34 0)
                                       (CONS 35 0)
                                       (CONS 36 0)
                                       (CONS 37 0)
                                       (CONS 38 0)
                                       (CONS 39 0)))
                          '(ARRAY (BVEC 20) 40)))
       (PP (LANE-LOOP-8 (RAC-TYPE-INFO 0 '(INT))
                        PP)))
   (IF1
     (SIZE)
     (B* ((B_ENCS (RAC-TYPE-INFO (AINIT (LIST (CONS 0 NIL)
                                              (CONS 1 NIL)
                                              (CONS 2 NIL)
                                              (CONS 3 NIL)))
                                 '(ARRAY (ARRAY (INT) 9) 4)))
          (PPS_ALIGNED
               (RAC-TYPE-INFO (AINIT (LIST (CONS 0
                                                 (AINIT (LIST (CONS 0 0)
                                                              (CONS 1 0)
                                                              (CONS 2 0)
                                                              (CONS 3 0)
                                                              (CONS 4 0)
                                                              (CONS 5 0)
                                                              (CONS 6 0)
                                                              (CONS 7 0)
                                                              (CONS 8 0))))
                                           (CONS 1
                                                 (AINIT (LIST (CONS 0 0)
                                                              (CONS 1 0)
                                                              (CONS 2 0)
                                                              (CONS 3 0)
                                                              (CONS 4 0)
                                                              (CONS 5 0)
                                                              (CONS 6 0)
                                                              (CONS 7 0)
                                                              (CONS 8 0))))
                                           (CONS 2
                                                 (AINIT (LIST (CONS 0 0)
                                                              (CONS 1 0)
                                                              (CONS 2 0)
                                                              (CONS 3 0)
                                                              (CONS 4 0)
                                                              (CONS 5 0)
                                                              (CONS 6 0)
                                                              (CONS 7 0)
                                                              (CONS 8 0))))
                                           (CONS 3
                                                 (AINIT (LIST (CONS 0 0)
                                                              (CONS 1 0)
                                                              (CONS 2 0)
                                                              (CONS 3 0)
                                                              (CONS 4 0)
                                                              (CONS 5 0)
                                                              (CONS 6 0)
                                                              (CONS 7 0)
                                                              (CONS 8 0))))))
                              '(ARRAY (ARRAY (BVEC 20) 9) 4)))
          ((MV B_ENCS PPS_ALIGNED)
           (LANE-LOOP-6 (RAC-TYPE-INFO 0 '(INT))
                        (A)
                        (OPA_UNSIGNED)
                        (B)
                        (OPB_UNSIGNED)
                        B_ENCS PPS_ALIGNED))
          (PP (LANE-LOOP-5 (RAC-TYPE-INFO 0 '(INT))
                           PPS_ALIGNED PP))
          (PP (AS 32
                  (BITS (- (AG 8 (AG 0 PPS_ALIGNED)) (ASH 1 18))
                        19 0)
                  PP))
          (PP (AS 32
                  (SETBITN (AG 32 PP)
                           20 0 (LOG< (AG 7 (AG 0 B_ENCS)) 0))
                  PP))
          (PP (AS 33 349536 PP))
          (PP (AS 34
                  (BITS (- (AG 8 (AG 1 PPS_ALIGNED)) (ASH 1 18))
                        19 0)
                  PP))
          (PP (AS 34
                  (SETBITN (AG 34 PP)
                           20 0 (LOG< (AG 7 (AG 1 B_ENCS)) 0))
                  PP))
          (PP (AS 36
                  (BITS (- (AG 8 (AG 2 PPS_ALIGNED)) (ASH 1 18))
                        19 0)
                  PP))
          (PP (AS 36
                  (SETBITN (AG 36 PP)
                           20 0 (LOG< (AG 7 (AG 2 B_ENCS)) 0))
                  PP))
          (PP (AS 38
                  (BITS (- (AG 8 (AG 3 PPS_ALIGNED)) (ASH 1 18))
                        19 0)
                  PP)))
       (AS 38
           (SETBITN (AG 38 PP)
                    20 0 (LOG< (AG 7 (AG 3 B_ENCS)) 0))
           PP))
     (B* ((A (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                         (CONS 1 0)
                                         (CONS 2 0)
                                         (CONS 3 0)
                                         (CONS 4 0)
                                         (CONS 5 0)
                                         (CONS 6 0)
                                         (CONS 7 0)))
                            '(ARRAY (BVEC 8) 8)))
          (B (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                         (CONS 1 0)
                                         (CONS 2 0)
                                         (CONS 3 0)
                                         (CONS 4 0)
                                         (CONS 5 0)
                                         (CONS 6 0)
                                         (CONS 7 0)))
                            '(ARRAY (BVEC 8) 8)))
          ((MV A B)
           (LANE-LOOP-4 (RAC-TYPE-INFO 0 '(INT))
                        (OPA)
                        (OPB)
                        A B))
          (B_ENCS (RAC-TYPE-INFO (AINIT (LIST (CONS 0 NIL)
                                              (CONS 1 NIL)
                                              (CONS 2 NIL)
                                              (CONS 3 NIL)
                                              (CONS 4 NIL)
                                              (CONS 5 NIL)
                                              (CONS 6 NIL)
                                              (CONS 7 NIL)))
                                 '(ARRAY (ARRAY (INT) 5) 8)))
          (PPS_ALIGNED
               (RAC-TYPE-INFO (AINIT (LIST (CONS 0
                                                 (AINIT (LIST (CONS 0 0)
                                                              (CONS 1 0)
                                                              (CONS 2 0)
                                                              (CONS 3 0)
                                                              (CONS 4 0))))
                                           (CONS 1
                                                 (AINIT (LIST (CONS 0 0)
                                                              (CONS 1 0)
                                                              (CONS 2 0)
                                                              (CONS 3 0)
                                                              (CONS 4 0))))
                                           (CONS 2
                                                 (AINIT (LIST (CONS 0 0)
                                                              (CONS 1 0)
                                                              (CONS 2 0)
                                                              (CONS 3 0)
                                                              (CONS 4 0))))
                                           (CONS 3
                                                 (AINIT (LIST (CONS 0 0)
                                                              (CONS 1 0)
                                                              (CONS 2 0)
                                                              (CONS 3 0)
                                                              (CONS 4 0))))
                                           (CONS 4
                                                 (AINIT (LIST (CONS 0 0)
                                                              (CONS 1 0)
                                                              (CONS 2 0)
                                                              (CONS 3 0)
                                                              (CONS 4 0))))
                                           (CONS 5
                                                 (AINIT (LIST (CONS 0 0)
                                                              (CONS 1 0)
                                                              (CONS 2 0)
                                                              (CONS 3 0)
                                                              (CONS 4 0))))
                                           (CONS 6
                                                 (AINIT (LIST (CONS 0 0)
                                                              (CONS 1 0)
                                                              (CONS 2 0)
                                                              (CONS 3 0)
                                                              (CONS 4 0))))
                                           (CONS 7
                                                 (AINIT (LIST (CONS 0 0)
                                                              (CONS 1 0)
                                                              (CONS 2 0)
                                                              (CONS 3 0)
                                                              (CONS 4 0))))))
                              '(ARRAY (ARRAY (BVEC 12) 5) 8)))
          ((MV B_ENCS PPS_ALIGNED)
           (LANE-LOOP-3 (RAC-TYPE-INFO 0 '(INT))
                        A (OPA_UNSIGNED)
                        B (OPB_UNSIGNED)
                        B_ENCS PPS_ALIGNED))
          (PP (LANE-LOOP-2 (RAC-TYPE-INFO 0 '(INT))
                           PPS_ALIGNED PP))
          (PP (LANE-LOOP-1 (RAC-TYPE-INFO 0 '(INT))
                           PPS_ALIGNED B_ENCS PP)))
       (AS 4 (BITS (+ (AG 4 PP) 704512) 19 0)
           PP)))))
 (DEFUNDD PPS NIL
          (B* ((L0PP (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                                 (CONS 1 0)
                                                 (CONS 2 0)
                                                 (CONS 3 0)
                                                 (CONS 4 0)
                                                 (CONS 5 0)
                                                 (CONS 6 0)
                                                 (CONS 7 0)
                                                 (CONS 8 0)
                                                 (CONS 9 0)
                                                 (CONS 10 0)
                                                 (CONS 11 0)
                                                 (CONS 12 0)
                                                 (CONS 13 0)
                                                 (CONS 14 0)
                                                 (CONS 15 0)
                                                 (CONS 16 0)
                                                 (CONS 17 0)
                                                 (CONS 18 0)
                                                 (CONS 19 0)
                                                 (CONS 20 0)
                                                 (CONS 21 0)
                                                 (CONS 22 0)
                                                 (CONS 23 0)
                                                 (CONS 24 0)
                                                 (CONS 25 0)
                                                 (CONS 26 0)
                                                 (CONS 27 0)
                                                 (CONS 28 0)
                                                 (CONS 29 0)
                                                 (CONS 30 0)
                                                 (CONS 31 0)
                                                 (CONS 32 0)
                                                 (CONS 33 0)
                                                 (CONS 34 0)
                                                 (CONS 35 0)
                                                 (CONS 36 0)
                                                 (CONS 37 0)
                                                 (CONS 38 0)
                                                 (CONS 39 0)))
                                    '(ARRAY (BVEC 36) 40)))
               (L0PP (LANE-LOOP-0 (RAC-TYPE-INFO 0 '(INT))
                                  L0PP))
               (L0PP (AS 0 (BITS (ASH (AG 35 (PP)) 14) 35 0)
                         L0PP))
               (L0PP (AS 1 (BITS (ASH (AG 37 (PP)) 14) 35 0)
                         L0PP))
               (L0PP (AS 2 (BITS (ASH (AG 39 (PP)) 14) 35 0)
                         L0PP))
               (L0PP (AS 3 (AG 0 (PP)) L0PP))
               (L0PP (AS 4 (AG 8 (PP)) L0PP))
               (L0PP (AS 5 (AG 16 (PP)) L0PP))
               (L0PP (AS 6 (AG 24 (PP)) L0PP))
               (L0PP (AS 7 (AG 1 (PP)) L0PP))
               (L0PP (AS 8 (AG 9 (PP)) L0PP))
               (L0PP (AS 9 (AG 17 (PP)) L0PP))
               (L0PP (AS 10 (AG 25 (PP)) L0PP))
               (L0PP (AS 11 (BITS (ASH (AG 2 (PP)) 2) 35 0)
                         L0PP))
               (L0PP (AS 12 (BITS (ASH (AG 10 (PP)) 2) 35 0)
                         L0PP))
               (L0PP (AS 13 (BITS (ASH (AG 18 (PP)) 2) 35 0)
                         L0PP))
               (L0PP (AS 14 (BITS (ASH (AG 26 (PP)) 2) 35 0)
                         L0PP))
               (L0PP (AS 15 (BITS (ASH (AG 3 (PP)) 4) 35 0)
                         L0PP))
               (L0PP (AS 16 (BITS (ASH (AG 11 (PP)) 4) 35 0)
                         L0PP))
               (L0PP (AS 17 (BITS (ASH (AG 19 (PP)) 4) 35 0)
                         L0PP))
               (L0PP (AS 18 (BITS (ASH (AG 27 (PP)) 4) 35 0)
                         L0PP))
               (L0PP (AS 19 (BITS (ASH (AG 4 (PP)) 6) 35 0)
                         L0PP))
               (L0PP (AS 20 (BITS (ASH (AG 12 (PP)) 6) 35 0)
                         L0PP))
               (L0PP (AS 21 (BITS (ASH (AG 20 (PP)) 6) 35 0)
                         L0PP))
               (L0PP (AS 22 (BITS (ASH (AG 28 (PP)) 6) 35 0)
                         L0PP))
               (L0PP (AS 23 (BITS (ASH (AG 5 (PP)) 8) 35 0)
                         L0PP))
               (L0PP (AS 24 (BITS (ASH (AG 13 (PP)) 8) 35 0)
                         L0PP))
               (L0PP (AS 25 (BITS (ASH (AG 21 (PP)) 8) 35 0)
                         L0PP))
               (L0PP (AS 26 (BITS (ASH (AG 29 (PP)) 8) 35 0)
                         L0PP))
               (L0PP (AS 27 (BITS (ASH (AG 6 (PP)) 10) 35 0)
                         L0PP))
               (L0PP (AS 28 (BITS (ASH (AG 14 (PP)) 10) 35 0)
                         L0PP))
               (L0PP (AS 29 (BITS (ASH (AG 22 (PP)) 10) 35 0)
                         L0PP))
               (L0PP (AS 30 (BITS (ASH (AG 30 (PP)) 10) 35 0)
                         L0PP))
               (L0PP (AS 31 (BITS (ASH (AG 7 (PP)) 12) 35 0)
                         L0PP))
               (L0PP (AS 32 (BITS (ASH (AG 15 (PP)) 12) 35 0)
                         L0PP))
               (L0PP (AS 33 (BITS (ASH (AG 23 (PP)) 12) 35 0)
                         L0PP))
               (L0PP (AS 34 (BITS (ASH (AG 31 (PP)) 12) 35 0)
                         L0PP))
               (L0PP (AS 35 (BITS (ASH (AG 32 (PP)) 14) 35 0)
                         L0PP))
               (L0PP (AS 36 (BITS (ASH (AG 34 (PP)) 14) 35 0)
                         L0PP))
               (L0PP (AS 37 (BITS (ASH (AG 36 (PP)) 14) 35 0)
                         L0PP))
               (L0PP (AS 38 (BITS (ASH (AG 38 (PP)) 14) 35 0)
                         L0PP))
               (L0PP (AS 39 (BITS (ASH (AG 33 (PP)) 14) 35 0)
                         L0PP)))
            (MV-NTH 0 (MV-LIST 2 (COMPRESS L0PP)))))
 (DEFUNDD PPC NIL
          (B* ((L0PP (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                                 (CONS 1 0)
                                                 (CONS 2 0)
                                                 (CONS 3 0)
                                                 (CONS 4 0)
                                                 (CONS 5 0)
                                                 (CONS 6 0)
                                                 (CONS 7 0)
                                                 (CONS 8 0)
                                                 (CONS 9 0)
                                                 (CONS 10 0)
                                                 (CONS 11 0)
                                                 (CONS 12 0)
                                                 (CONS 13 0)
                                                 (CONS 14 0)
                                                 (CONS 15 0)
                                                 (CONS 16 0)
                                                 (CONS 17 0)
                                                 (CONS 18 0)
                                                 (CONS 19 0)
                                                 (CONS 20 0)
                                                 (CONS 21 0)
                                                 (CONS 22 0)
                                                 (CONS 23 0)
                                                 (CONS 24 0)
                                                 (CONS 25 0)
                                                 (CONS 26 0)
                                                 (CONS 27 0)
                                                 (CONS 28 0)
                                                 (CONS 29 0)
                                                 (CONS 30 0)
                                                 (CONS 31 0)
                                                 (CONS 32 0)
                                                 (CONS 33 0)
                                                 (CONS 34 0)
                                                 (CONS 35 0)
                                                 (CONS 36 0)
                                                 (CONS 37 0)
                                                 (CONS 38 0)
                                                 (CONS 39 0)))
                                    '(ARRAY (BVEC 36) 40)))
               (L0PP (LANE-LOOP-0 (RAC-TYPE-INFO 0 '(INT))
                                  L0PP))
               (L0PP (AS 0 (BITS (ASH (AG 35 (PP)) 14) 35 0)
                         L0PP))
               (L0PP (AS 1 (BITS (ASH (AG 37 (PP)) 14) 35 0)
                         L0PP))
               (L0PP (AS 2 (BITS (ASH (AG 39 (PP)) 14) 35 0)
                         L0PP))
               (L0PP (AS 3 (AG 0 (PP)) L0PP))
               (L0PP (AS 4 (AG 8 (PP)) L0PP))
               (L0PP (AS 5 (AG 16 (PP)) L0PP))
               (L0PP (AS 6 (AG 24 (PP)) L0PP))
               (L0PP (AS 7 (AG 1 (PP)) L0PP))
               (L0PP (AS 8 (AG 9 (PP)) L0PP))
               (L0PP (AS 9 (AG 17 (PP)) L0PP))
               (L0PP (AS 10 (AG 25 (PP)) L0PP))
               (L0PP (AS 11 (BITS (ASH (AG 2 (PP)) 2) 35 0)
                         L0PP))
               (L0PP (AS 12 (BITS (ASH (AG 10 (PP)) 2) 35 0)
                         L0PP))
               (L0PP (AS 13 (BITS (ASH (AG 18 (PP)) 2) 35 0)
                         L0PP))
               (L0PP (AS 14 (BITS (ASH (AG 26 (PP)) 2) 35 0)
                         L0PP))
               (L0PP (AS 15 (BITS (ASH (AG 3 (PP)) 4) 35 0)
                         L0PP))
               (L0PP (AS 16 (BITS (ASH (AG 11 (PP)) 4) 35 0)
                         L0PP))
               (L0PP (AS 17 (BITS (ASH (AG 19 (PP)) 4) 35 0)
                         L0PP))
               (L0PP (AS 18 (BITS (ASH (AG 27 (PP)) 4) 35 0)
                         L0PP))
               (L0PP (AS 19 (BITS (ASH (AG 4 (PP)) 6) 35 0)
                         L0PP))
               (L0PP (AS 20 (BITS (ASH (AG 12 (PP)) 6) 35 0)
                         L0PP))
               (L0PP (AS 21 (BITS (ASH (AG 20 (PP)) 6) 35 0)
                         L0PP))
               (L0PP (AS 22 (BITS (ASH (AG 28 (PP)) 6) 35 0)
                         L0PP))
               (L0PP (AS 23 (BITS (ASH (AG 5 (PP)) 8) 35 0)
                         L0PP))
               (L0PP (AS 24 (BITS (ASH (AG 13 (PP)) 8) 35 0)
                         L0PP))
               (L0PP (AS 25 (BITS (ASH (AG 21 (PP)) 8) 35 0)
                         L0PP))
               (L0PP (AS 26 (BITS (ASH (AG 29 (PP)) 8) 35 0)
                         L0PP))
               (L0PP (AS 27 (BITS (ASH (AG 6 (PP)) 10) 35 0)
                         L0PP))
               (L0PP (AS 28 (BITS (ASH (AG 14 (PP)) 10) 35 0)
                         L0PP))
               (L0PP (AS 29 (BITS (ASH (AG 22 (PP)) 10) 35 0)
                         L0PP))
               (L0PP (AS 30 (BITS (ASH (AG 30 (PP)) 10) 35 0)
                         L0PP))
               (L0PP (AS 31 (BITS (ASH (AG 7 (PP)) 12) 35 0)
                         L0PP))
               (L0PP (AS 32 (BITS (ASH (AG 15 (PP)) 12) 35 0)
                         L0PP))
               (L0PP (AS 33 (BITS (ASH (AG 23 (PP)) 12) 35 0)
                         L0PP))
               (L0PP (AS 34 (BITS (ASH (AG 31 (PP)) 12) 35 0)
                         L0PP))
               (L0PP (AS 35 (BITS (ASH (AG 32 (PP)) 14) 35 0)
                         L0PP))
               (L0PP (AS 36 (BITS (ASH (AG 34 (PP)) 14) 35 0)
                         L0PP))
               (L0PP (AS 37 (BITS (ASH (AG 36 (PP)) 14) 35 0)
                         L0PP))
               (L0PP (AS 38 (BITS (ASH (AG 38 (PP)) 14) 35 0)
                         L0PP))
               (L0PP (AS 39 (BITS (ASH (AG 33 (PP)) 14) 35 0)
                         L0PP)))
            (MV-NTH 1 (MV-LIST 2 (COMPRESS L0PP)))))
 (DEFUNDD LANE-RES NIL
          (IF1 (WITHOUT_VDOT16)
               (B* ((L0PP (RAC-TYPE-INFO (CONVERT_PP (PP))
                                         '(ARRAY (BVEC 21) 40)))
                    ((MV PPS PPC)
                     (COMPRESS_WITHOUT_VDOT16 L0PP))
                    (SUM_PP (RAC-TYPE-INFO (BITS (+ PPS PPC) 20 0)
                                           '(BVEC 21))))
                 (BITS (+ (+ SUM_PP (ACC)) 4293918720)
                       63 0))
               (B* ((SUM_PP (RAC-TYPE-INFO (BITS (+ (PPS) (PPC)) 35 0)
                                           '(BVEC 36))))
                 (IF1 (SIZE)
                      (BITS (+ (+ SUM_PP (ACC))
                               18446744039349813248)
                            63 0)
                      (BITS (+ (+ (ASH SUM_PP (- 8))
                                  18446744073708503040)
                               (ACC))
                            63 0)))))

(defthm lane-loop-7-type
  (implies (and (is-type-p elem '(int))
                (is-type-p opa '(bvec 64))
                (is-type-p opb '(bvec 64))
                (is-type-p a '(array (bvec 16) 4))
                (is-type-p b '(array (bvec 16) 4)))
           (and (is-type-p (mv-nth 0 (lane-loop-7 elem opa opb a b)) '(array (bvec 16) 4))
                (is-type-p (mv-nth 1 (lane-loop-7 elem opa opb a b)) '(array (bvec 16) 4))))
  :hints (("Goal"
           :in-theory '(lane-loop-7 type-theory))))

(defthm a-type
  (is-type-p (a) '(array (bvec 16) 4))
  :hints (("Goal"
           :in-theory (enable a type-theory lane-loop-7-type inputs-ok))))

(defthm b-type
  (is-type-p (b) '(array (bvec 16) 4))
  :hints (("Goal"
           :in-theory (enable b type-theory lane-loop-7-type inputs-ok))))

(defthm lane-loop-1-type
  (implies (and (is-type-p elem '(int))
                (is-type-p pps_aligned '(array (array (bvec 20) 9) 4))
                (is-type-p b_enc '(array (array (int) 4) 9))
                (is-type-p pp '(array (bvec 20) 40)))
           (is-type-p (lane-loop-1 elem pps_aligned b_encs pp)
                      '(array (bvec 20) 40)))
  :hints (("Goal"
           :in-theory '(lane-loop-1 type-theory))))

;(defthm pp-type
;  (is-type-p (pp) '(array (bvec 20) 40))
;  :hints (("Goal"
;           :in-theory '(pp type-theory))))

; (DEFTHMD LANE-LEMMA
;   (EQUAL (LANE-RES)
;          (LANE (OPA)
;                (OPB)
;                (ACC)
;                (OPA_UNSIGNED)
;                (OPB_UNSIGNED)
;                (SIZE)
;                (WITHOUT_VDOT16)))
;   :HINTS (("Goal" :IN-THEORY NIL
;                   :DO-NOT '(PREPROCESS)
;                   :CLAUSE-PROCESSOR
;                   (EXPAND-REDUCE-CP CLAUSE '(T LANE-RES A B PP PPS PPC LANE)
;                                     STATE)))))
