(IN-PACKAGE "RTL")

(INCLUDE-BOOK "rtl/rel11/lib/rac" :DIR :SYSTEM)

(SET-IGNORE-OK T)

(SET-IRRELEVANT-FORMALS-OK T)

(defun RAC-TYPE-INFO (x type) x)

(defun ENCODE (SLICE)
        (LET ((ENC (RAC-TYPE-INFO 0 '(BVEC 3))))
             (CASE SLICE
                   (4 6)
                   ((5 6) 5)
                   ((7 0) 0)
                   ((1 2) 1)
                   (3 2)
                   (T (LET ((ASSERT (IN-FUNCTION ENCODE (FALSE$))))
                           ENC)))))

(defun BOOTH-LOOP-0 (K X35 A)
        (DECLARE (XARGS :MEASURE (NFIX (- 17 K))))
        (IF (AND (INTEGERP K) (< K 17))
            (LET ((A (AS K
                         (ENCODE (BITS X35 (+ (* 2 K) (- 3 1)) (* 2 K)))
                         A)))
                 (BOOTH-LOOP-0 (+ K 1) X35 A))
            A))

(defun BOOTH (X)
        (LET ((X35 (RAC-TYPE-INFO (BITS (ASH X 1) 34 0)
                                  '(BVEC 35)))
              (A (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                             (CONS 1 0)
                                             (CONS 2 0)
                                             (CONS 3 0)
                                             (CONS 4 0)
                                             (CONS 5 0)
                                             (CONS 6 0)
                                             (CONS 7 0)
                                             (CONS 8 0)
                                             (CONS 9 0)
                                             (CONS 10 0)
                                             (CONS 11 0)
                                             (CONS 12 0)
                                             (CONS 13 0)
                                             (CONS 14 0)
                                             (CONS 15 0)
                                             (CONS 16 0)))
                                '(ARRAY (BVEC 3) 17))))
             (BOOTH-LOOP-0 (RAC-TYPE-INFO 0 'INT)
                           X35 A)))

(defun PARTIALPRODUCTS-LOOP-0 (K Y M21 PP)
        (DECLARE (XARGS :MEASURE (NFIX (- 17 K))))
        (IF (AND (INTEGERP K) (< K 17))
            (LET* ((ROW (RAC-TYPE-INFO 0 '(BVEC 33)))
                   (ROW (CASE (BITS (AG K M21) 1 0)
                              (2 (BITS (ASH Y 1) 32 0))
                              (1 Y)
                              (T 0)))
                   (PP (AS K
                           (IF1 (BITN (AG K M21) 2)
                                (BITS (LOGNOT ROW) 32 0)
                                ROW)
                           PP)))
                  (PARTIALPRODUCTS-LOOP-0 (+ K 1)
                                          Y M21 PP))
            PP))

(defun PARTIALPRODUCTS (M21 Y)
        (LET ((PP (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                              (CONS 1 0)
                                              (CONS 2 0)
                                              (CONS 3 0)
                                              (CONS 4 0)
                                              (CONS 5 0)
                                              (CONS 6 0)
                                              (CONS 7 0)
                                              (CONS 8 0)
                                              (CONS 9 0)
                                              (CONS 10 0)
                                              (CONS 11 0)
                                              (CONS 12 0)
                                              (CONS 13 0)
                                              (CONS 14 0)
                                              (CONS 15 0)
                                              (CONS 16 0)))
                                 '(ARRAY (BVEC 33) 17))))
             (PARTIALPRODUCTS-LOOP-0 (RAC-TYPE-INFO 0 'INT)
                                     Y M21 PP)))

(defun ALIGN-LOOP-0 (K PPS PSB SB TBLE)
        (DECLARE (XARGS :MEASURE (NFIX (- 17 K))))
        (IF (AND (INTEGERP K) (< K 17))
            (LET* ((TMP (RAC-TYPE-INFO 0 '(BVEC 67)))
                   (TMP (SETBITS TMP 67 (+ (* 2 K) (- 33 1))
                                 (* 2 K)
                                 (AG K PPS)))
                   (TMP (IF1 (LOG= K 0)
                             (LET* ((TMP (SETBITN TMP 67 33 (AG K SB)))
                                    (TMP (SETBITN TMP 67 34 (AG K SB))))
                                   (SETBITN TMP 67 35 (LOGNOT1 (AG K SB))))
                             (LET* ((TMP (SETBITN TMP 67 (- (* 2 K) 2)
                                                  (AG K PSB)))
                                    (TMP (SETBITN TMP 67 (+ (* 2 K) 33)
                                                  (LOGNOT1 (AG K SB)))))
                                   (SETBITN TMP 67 (+ (* 2 K) 34) 1))))
                   (TBLE (AS K (BITS TMP 63 0) TBLE)))
                  (ALIGN-LOOP-0 (+ K 1) PPS PSB SB TBLE))
            TBLE))

(defun ALIGN-LOOP-1 (K BDS SB PSB)
        (DECLARE (XARGS :MEASURE (NFIX (- 17 K))))
        (IF (AND (INTEGERP K) (< K 17))
            (LET ((SB (AS K (BITN (AG K BDS) 2) SB))
                  (PSB (AS (+ K 1) (BITN (AG K BDS) 2) PSB)))
                 (ALIGN-LOOP-1 (+ K 1) BDS SB PSB))
            (MV SB PSB)))

(defun ALIGN (BDS PPS)
        (LET ((SB (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                              (CONS 1 0)
                                              (CONS 2 0)
                                              (CONS 3 0)
                                              (CONS 4 0)
                                              (CONS 5 0)
                                              (CONS 6 0)
                                              (CONS 7 0)
                                              (CONS 8 0)
                                              (CONS 9 0)
                                              (CONS 10 0)
                                              (CONS 11 0)
                                              (CONS 12 0)
                                              (CONS 13 0)
                                              (CONS 14 0)
                                              (CONS 15 0)
                                              (CONS 16 0)))
                                 '(ARRAY BOOL 17)))
              (PSB (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                               (CONS 1 0)
                                               (CONS 2 0)
                                               (CONS 3 0)
                                               (CONS 4 0)
                                               (CONS 5 0)
                                               (CONS 6 0)
                                               (CONS 7 0)
                                               (CONS 8 0)
                                               (CONS 9 0)
                                               (CONS 10 0)
                                               (CONS 11 0)
                                               (CONS 12 0)
                                               (CONS 13 0)
                                               (CONS 14 0)
                                               (CONS 15 0)
                                               (CONS 16 0)
                                               (CONS 17 0)))
                                  '(ARRAY BOOL 18))))
             (MV-LET (SB PSB)
                     (ALIGN-LOOP-1 (RAC-TYPE-INFO 0 'INT)
                                   BDS SB PSB)
                     (LET ((TBLE (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                                             (CONS 1 0)
                                                             (CONS 2 0)
                                                             (CONS 3 0)
                                                             (CONS 4 0)
                                                             (CONS 5 0)
                                                             (CONS 6 0)
                                                             (CONS 7 0)
                                                             (CONS 8 0)
                                                             (CONS 9 0)
                                                             (CONS 10 0)
                                                             (CONS 11 0)
                                                             (CONS 12 0)
                                                             (CONS 13 0)
                                                             (CONS 14 0)
                                                             (CONS 15 0)
                                                             (CONS 16 0)))
                                                '(ARRAY (BVEC 64) 17))))
                          (ALIGN-LOOP-0 (RAC-TYPE-INFO 0 'INT)
                                        PPS PSB SB TBLE)))))

(defun COMPRESS32 (IN0 IN1 IN2)
        (MV (RAC-TYPE-INFO (LOGXOR (LOGXOR IN0 IN1) IN2)
                           '(BVEC 64))
            (BITS (ASH (RAC-TYPE-INFO (LOGIOR (LOGIOR (LOGAND IN0 IN1)
                                                      (LOGAND IN0 IN2))
                                              (LOGAND IN1 IN2))
                                      '(BVEC 64))
                       1)
                  63 0)))

(defun COMPRESS42 (IN0 IN1 IN2 IN3)
        (LET ((TEMP (RAC-TYPE-INFO (BITS (ASH (LOGIOR (LOGIOR (LOGAND IN1 IN2)
                                                              (LOGAND IN1 IN3))
                                                      (LOGAND IN2 IN3))
                                              1)
                                         63 0)
                                   '(BVEC 64))))
             (MV
               (RAC-TYPE-INFO (LOGXOR (LOGXOR (LOGXOR (LOGXOR IN0 IN1) IN2)
                                              IN3)
                                      TEMP)
                              '(BVEC 64))
               (BITS
                 (ASH
                   (RAC-TYPE-INFO
                     (BITS (LOGIOR (LOGAND IN0
                                           (LOGNOT (LOGXOR (LOGXOR (LOGXOR IN0 IN1) IN2)
                                                           IN3)))
                                   (LOGAND TEMP
                                           (LOGXOR (LOGXOR (LOGXOR IN0 IN1) IN2)
                                                   IN3)))
                           63 0)
                     '(BVEC 64))
                   1)
                 63 0))))

(defun SUM-LOOP-0 (I A1 A2)
        (DECLARE (XARGS :MEASURE (NFIX (- 2 I))))
        (IF (AND (INTEGERP I) (< I 2))
            (LET ((A2 (LET ((TEMP-1 NIL) (TEMP-0 NIL))
                           (MV-LET (TEMP-0 TEMP-1)
                                   (COMPRESS42 (AG (* 4 I) A1)
                                               (AG (+ (* 4 I) 1) A1)
                                               (AG (+ (* 4 I) 2) A1)
                                               (AG (+ (* 4 I) 3) A1))
                                   (LET ((A2 (AS (+ (* 2 I) 0) TEMP-0 A2)))
                                        (AS (+ (* 2 I) 1) TEMP-1 A2))))))
                 (SUM-LOOP-0 (+ I 1) A1 A2))
            A2))

(defun SUM-LOOP-1 (I IN A1)
        (DECLARE (XARGS :MEASURE (NFIX (- 4 I))))
        (IF (AND (INTEGERP I) (< I 4))
            (LET ((A1 (LET ((TEMP-1 NIL) (TEMP-0 NIL))
                           (MV-LET (TEMP-0 TEMP-1)
                                   (COMPRESS42 (AG (* 4 I) IN)
                                               (AG (+ (* 4 I) 1) IN)
                                               (AG (+ (* 4 I) 2) IN)
                                               (AG (+ (* 4 I) 3) IN))
                                   (LET ((A1 (AS (+ (* 2 I) 0) TEMP-0 A1)))
                                        (AS (+ (* 2 I) 1) TEMP-1 A1))))))
                 (SUM-LOOP-1 (+ I 1) IN A1))
            A1))

(defun SUM (IN)
        (LET* ((A1 (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                               (CONS 1 0)
                                               (CONS 2 0)
                                               (CONS 3 0)
                                               (CONS 4 0)
                                               (CONS 5 0)
                                               (CONS 6 0)
                                               (CONS 7 0)))
                                  '(ARRAY (BVEC 64) 8)))
               (A1 (SUM-LOOP-1 (RAC-TYPE-INFO 0 'INT)
                               IN A1))
               (A2 (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0)
                                               (CONS 1 0)
                                               (CONS 2 0)
                                               (CONS 3 0)))
                                  '(ARRAY (BVEC 64) 4)))
               (A2 (SUM-LOOP-0 (RAC-TYPE-INFO 0 'INT)
                               A1 A2))
               (A3 (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0) (CONS 1 0)))
                                  '(ARRAY (BVEC 64) 2)))
               (A3 (LET ((TEMP-1 NIL) (TEMP-0 NIL))
                        (MV-LET (TEMP-0 TEMP-1)
                                (COMPRESS42 (AG 0 A2)
                                            (AG 1 A2)
                                            (AG 2 A2)
                                            (AG 3 A2))
                                (LET ((A3 (AS 0 TEMP-0 A3)))
                                     (AS 1 TEMP-1 A3)))))
               (A4 (RAC-TYPE-INFO (AINIT (LIST (CONS 0 0) (CONS 1 0)))
                                  '(ARRAY (BVEC 64) 2)))
               (A4 (LET ((TEMP-1 NIL) (TEMP-0 NIL))
                        (MV-LET (TEMP-0 TEMP-1)
                                (COMPRESS32 (AG 0 A3)
                                            (AG 1 A3)
                                            (AG 16 IN))
                                (LET ((A4 (AS 0 TEMP-0 A4)))
                                     (AS 1 TEMP-1 A4))))))
              (BITS (+ (AG 0 A4) (AG 1 A4)) 63 0)))

(defun IMUL (S1 S2)
        (LET* ((BD (RAC-TYPE-INFO (BOOTH S1)
                                  '(ARRAY (BVEC 3) 17)))
               (PP (RAC-TYPE-INFO (PARTIALPRODUCTS BD S2)
                                  '(ARRAY (BVEC 33) 17)))
               (TBLE (RAC-TYPE-INFO (ALIGN BD PP)
                                    '(ARRAY (BVEC 64) 17))))
              (RAC-TYPE-INFO (SUM TBLE) '(BVEC 64))))

(defun IMULTEST (S1 S2)
        (LET ((SPEC_RESULT (RAC-TYPE-INFO (* S1 S2) '(BVEC 64)))
              (IMUL_RESULT (RAC-TYPE-INFO (IMUL S1 S2)
                                          '(BVEC 64))))
             (MV (LOG= SPEC_RESULT IMUL_RESULT)
                 SPEC_RESULT IMUL_RESULT)))

